services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PAYLOAD_SECRET=${PAYLOAD_SECRET}
        - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - media:/app/public

  postgres:
    image: postgis/postgis:17-3.5-alpine
    platform: linux/amd64
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payload
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
  media:
